name: Plugin/mod incompatibility or other bug
description: Report a bug or plugin/mod incompatibility here
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug and how to replicate it
      description: A video or detailed instructions to help replicate the issue would help.
      placeholder: |
        Step 1. Do this
        Step 2. Then do this
        Step 3. etc...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Grim version
      description: Provide the version of Grim running on the server. You can run `/grim version` to check.
      placeholder: Examples include 2.3.73-8ddd7f1, 2.3.72, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server version
      description: |
        Run `/version` on your server to check. Provide both the server type (ie Paper, Airplane, etc) & the Minecraft version.
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Affected Platform(s)
      description: Which platforms does this issue affect? If you aren't sure, select both.
      options:
        - "Bukkit"
        - "Fabric"
      multiple: true
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins/Mods
      description: |
        List all plugins or mods installed on your server. To list plugins on Bukkit-based servers, run `/plugins`.
        If your server is behind a proxy such as Bungeecord, you should list the proxy's plugins as well.
    validations:
      required: true
